tasks:
  - name: download library
    init: mvn spotless:apply verify
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
    - donjayamanne.githistory
    - anwar.papyrus-pdf
github:
  prebuilds:
    pullRequests: false
    addComment: false
    addCheck: false
