tasks:
  - name: download library
    init: mvn spotless:apply verify
github:
  prebuilds:
    pullRequests: false
    addComment: false
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - donjayamanne.githistory
    - github.vscode-pull-request-github
    - vscjava.vscode-java-pack
    - ritwickdey.liveserver
    - anwar.papyrus-pdf
