# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create a package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Verify with Maven
      run: mvn verify --file pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload jacoco result
      uses: actions/upload-artifact@v2
      with:
        name: jacoco
        path: target/site/jacoco
