name: Release version

on:
  pull_request:
    types:
      - opened
    branches: 
      - release

jobs:
  release_version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Git setting
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
    - name: Change to release version
      run: sed -i -e 's/-SNAPSHOT//' pom.xml
    - name: Create Tag name
      id: project
      run: |
        echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - name: Create branch
      run: |
        git checkout -b release_version/${{ steps.project.outputs.version }}
        git push --set-upstream origin release_version/${{ steps.project.outputs.version }}
    - name: Commit pom.xml
      run: |
        git commit -m "release version pom.xml" -a
        git push origin
    - name: Create release version PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr create -B main -t "Change release version" -b ""
